# Generated by Django 4.2.1 on 2023-05-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("permalink", models.CharField(max_length=255)),
                ("items", models.ManyToManyField(to="items.item")),
            ],
        ),
    ]
