# Generated by Django 4.2.1 on 2023-06-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "002_extensions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-version_created_at"]},
        ),
        migrations.AddField(
            model_name="user",
            name="items_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
