# Generated by Django 4.2.1 on 2023-06-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "002_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="downloads_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
