# Generated by Django 4.2.2 on 2023-07-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "002_extensions"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("link__isnull", False), ("file__isnull", False), _connector="OR"
                ),
                name="version_must_have_link_or_file",
            ),
        ),
    ]
