# Generated by Django 4.2.2 on 2023-07-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_version_version_must_have_link_or_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="byline",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="topnote",
            field=models.TextField(blank=True, null=True),
        ),
    ]
