# Generated by Django 4.2.2 on 2023-07-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_item_byline_item_topnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
