# Generated by Django 4.2.1 on 2023-06-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_alter_version_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="screenshots/"),
        ),
        migrations.AddField(
            model_name="version",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="versions/"),
        ),
    ]
