# Generated by Django 4.2.2 on 2023-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_alter_version_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
