# Generated by Django 4.2.2 on 2023-07-28 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0006_screenshot_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="screenshot",
            options={"ordering": ["order", "-created_at"]},
        ),
    ]
