# Generated by Django 4.2.1 on 2023-06-03 01:21

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0007_remove_tag_items_item_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenshot",
            name="file",
            field=models.ImageField(
                blank=True, null=True, upload_to=items.models.get_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="version",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=items.models.get_upload_path
            ),
        ),
    ]
