# Generated by Django 4.2.2 on 2023-08-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0007_alter_screenshot_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
